---
title: "Vignette Title"
author: "Andrew Stewart"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(ggimage)
library(colorr)
```

```{r}
(pal = nhl.colors("ducks"))
pie(rep(1, length(pal)), labels = sprintf("%d (%s)", seq_along(pal), pal), col = pal)
```

Inspired by https://rpubs.com/maraaverick/poke_nba_medians


```{r fig.height=6, fig.width=6}
library("ggplot2")
library("ggimage")
library(hrbrthemes)

# create a df

set.seed(2017-02-21)
d <- data.frame(x = rnorm(10),
                y = rnorm(10),
                image = sample(c("http://icons.iconarchive.com/icons/bo/nhl/32/Edmonton-Oilers-icon.png",                                "http://icons.iconarchive.com/icons/bo/nhl/32/Buffalo-Sabres-95-icon.png"),
                               size=10, replace = TRUE)
                )
# plot2
ggplot(d, aes(x, y)) + 
  geom_image(aes(image=image))
  # theme_ipsum_rc()
```


```{r}
teams <- data.frame(x=rnorm(4),
                    y=rnorm(4),
                    logo=c(
                      "/Users/andrew/Code/nhlplots/inst/logos/Buffalo.png",
                      "/Users/andrew/Code/nhlplots/inst/logos/Florida.png",
                      "/Users/andrew/Code/nhlplots/inst/logos/Vegas.png",
                      "/Users/andrew/Code/nhlplots/inst/logos/Vancouver.png"
                    ))

ggplot(teams, aes(x, y)) +
  geom_image(aes(image=logo)) +
  # coord_fixed() + 
  theme(aspect.ratio=1)
```

```{r}
geom_nhl <- function(mapping=NULL, data=NULL, inherit.aes=TRUE,
                         na.rm=FALSE, by="width", ...) {
  geom_image(mapping, data, inherit.aes=inherit.aes, na.rm=na.rm, ..., geom = 'nhl')
}
```

```{r}
teams <- data.frame(x=rnorm(4),
                    y=rnorm(4),
                    logo=c(
                      "/Users/andrew/Code/nhlplots/inst/logos/Buffalo.png",
                      "/Users/andrew/Code/nhlplots/inst/logos/Florida.png",
                      "/Users/andrew/Code/nhlplots/inst/logos/Vegas.png",
                      "/Users/andrew/Code/nhlplots/inst/logos/Vancouver.png"
                    ))

ggplot(teams, aes(x, y)) +
  geom_nhl(aes(image = logo)) +
  # theme(aspect.ratio=1) +
  labs(x = "points scored", 
       y = "points allowed", 
       title="Median Points in Paint", 
       subtitle="NBA teams x Pokémon, per game") +
  coord_fixed() +
  theme_bw()
```




```{r}
# devtools::load_all()

system.file("extdata", "mydata.csv", package = "nhlplots")
```

